# -*- coding: utf-8 -*-
"""MedicalChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXwok5NtlDFPTUN1XQ5TXgesDGxK8HjL

# **Build BioMistral Medical RAG Chatbot using BioMistral Open Source LLM**

##Load the google drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Installation"""

!pip install langchain sentence-transformers chromadb llama-cpp-python langchain_community pypdf

"""## Importing Libraries"""

from langchain_community.document_loaders import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import Chroma
from langchain_community.llms import LlamaCpp
from langchain.chains import RetrievalQA, LLMChain

"""## Import the Document"""

loader = PyPDFDirectoryLoader("/content/drive/MyDrive/dataset")
docs = loader.load()

len(docs)

docs[85]

"""## Chunking"""

text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=50)
chunks = text_splitter.split_documents(docs)

len(chunks)

chunks[78]

"""## Embeddings Creation"""

import os
os.environ['HUGGINGFACEHUB_API_TOKEN'] = "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"

embeddings = SentenceTransformerEmbeddings(model_name="NeuML/pubmedbert-base-embeddings")

"""## Vector Store Creation"""

vectorstore = Chroma.from_documents(chunks, embeddings)

query = "Who is at risk of heart disease?"

search_results = vectorstore.similarity_search(query)

search_results

retriever = vectorstore.as_retriever(search_kwargs={'k':5})

retriever.get_relevant_documents(query)

"""## Loading LLM Model"""

llm = LlamaCpp(
    model_path="/content/drive/MyDrive/dataset/BioMistral-7B.Q4_K_M.gguf",
    temperature=0.2,
    max_tokens = 2048,
    top_p=1
)

"""## Use LLM and retriver and query, to generate final response"""

template = """
<|context|>
You are an Medical Assistant that follows the instructions and generate the accurate response based on the query and the context provided.
Please be truthful and give direct answers.

<|user|>
{query}

<|assistant|>
"""

from langchain.schema.runnable import RunnablePassthrough
from langchain.schema.output_parser import StrOutputParser
from langchain.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template(template)

rag_chain = (
    {"context": retriever, "query": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

response=rag_chain.invoke(query)

response

import sys

while True:
  user_input = input(f"Input query: ")
  if user_input == 'exit':
    print("Exiting...")
    sys.exit()
  if user_input=="":
    continue
  result = rag_chain.invoke(user_input)
  print("Answer: ", result)